config/routes.rb
Litsocial::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users, :only => []
  devise_scope :user do
    get     '/sign_in'         => 'devise/sessions#new',          as: :new_user_session
    post    '/sign_in'         => 'devise/sessions#create',       as: :user_session
    delete  '/sign_out'        => 'devise/sessions#destroy',      as: :destroy_user_session
    post    '/forgot_password' => 'devise/passwords#create',      as: :user_password
    get     '/forgot_password' => 'devise/passwords#new',         as: :new_user_password
    get     '/reset_password'  => 'devise/passwords#edit',        as: :edit_user_password
    put     '/reset_password'  => 'devise/passwords#update'
    post    '/sign_up'         => 'devise/registrations#create',  as: :user_registration
    get     '/sign_up'         => 'devise/registrations#new',     as: :new_user_registration

  end

  resources :stories do 
    member do 
      post :kindle
      get :kindle_preview
    end
  end
  resources :series do 
    member do 
      post :kindle
      get :kindle_preview
    end
  end
  resources :journals
  resources :pages, only: [:index, :show]
  resources :news_posts, only: [:index, :show], path: 'news' do 
    collection do 
      get :archive
    end
  end
  resources :users, only: [:index, :show] do 
    member do 
      get :stories
      get :series
      get :journals
    end
  end

  get 'forums/categories/:id' => 'forum_posts#category', as: :forum_category
  resources :forum_posts, path: 'forums'

  get 'account'         => 'account#show',    as: :account

  %w[stories journals forums watches favs bookmarks notifications edit cancel].each do |name|
    get "account/#{name}" => "account##{name}", as: "#{name}_account"
  end
  put 'account'         => 'account#update'
  delete 'account'      => 'account#destroy'

  resources :messages, :path => "/account/messages", except: [:edit, :update] do
    member do 
      put :report
      post :toggle
    end
    collection do 
      get :sent
      get :unread
      get :read
    end
  end
  resources :notifications, :path => '/account/notifications', only: [:destroy]
  resources :watches, only: [:create, :destroy]
  resources :favs, only: [:create, :destroy]
  resources :reports, only: [:create]

  get    'bookmarks/import' => 'bookmarks#import', as: :import_bookmarks
  post   'bookmarks/import' => 'bookmarks#import'
  put    'bookmarks/:story_id/:paragraph' => 'bookmarks#create_or_update', as: :bookmark
  delete 'bookmarks/:story_id' => 'bookmarks#destroy', as: :clear_bookmark

  resources :comments

  post 'convert_word_doc' => 'home#convert_word_doc', as: :convert_word_doc
  post 'user_lookup' => 'home#user_lookup', as: :user_lookup

  root :to => 'home#index'

end

app/views/shared/_banners.html.haml
:ruby 
  # Required: record
  type_name = record.class.name.humanize.downcase

-if record.respond_to?(:deleted?) && record.deleted?
  .alert.alert-warning.alert-tight
    %p
      %strong This #{type_name} has been deleted
-elsif record.respond_to?(:locked?) && record.locked?
  .alert.alert-warning.alert-tight
    %p
      %strong This #{type_name} has been locked
    =rich record.locked_reason if record.respond_to? :locked_reason
-elsif owner?(record)
  .alert.alert-info.alert-tight.hidden-phone
    %p
      You are the owner, so you may
      -if Series === record
        #{link_to "edit this #{type_name}", [:edit, record]}
        or #{link_to "add a story", new_story_path(:series => record.id)}
      -elsif Story === record && record.series?
        #{link_to "edit this #{type_name}", [:edit, record]},
        #{link_to "edit this series", edit_series_path(record.series_id)},
        or #{link_to "add a story", new_story_path(:series => record.series_id)} to it
      -else
        =link_to "edit this #{type_name}", [:edit, record]

app/views/shared/_fav_link.html.haml
:ruby
  #required: favable or (@fav and @favable)
  #optional: button_size
  button_size ||= "mini"
  fav = if @fav # In watchescontroller
    favable = @favable
    @fav.persisted? ? @fav : nil
  elsif user_signed_in?
    current_user.faving?(favable)
  end
  js_id = String.random
  css = "btn btn-warning btn-#{button_size}"
%span{id:js_id}
  -if user_signed_in? 
    -if fav
      =icon_link "remove icon-white", "Unfav", '#', class:css, data:{widget:"unfav-link", replace:"##{js_id}", id:fav.id}
    -else
      =icon_link "heart icon-white", "Fav", '#', class:css, data:{widget:"fav-link", replace:"##{js_id}", class:favable.class.name, id:favable.id}
  -else
    Sign in to fav

app/views/shared/_literature_form.html.haml
%p 
  If you don't want to deal with copying and pasting your story, you can 
  =link_to "upload an MS Word or OpenOffice Writer document", '#', data:{target:'#word_doc_uploader', toggle:'modal'}
  and we'll copy and paste the text for you.
=tb_form_for literature, html:{class:'form-horizontal'} do |f|
  =continue_redirect
  =f.inputs do
    =f.text_field :title
    =f.text_area :contents, :data => {:widget => 'ckeditor'}, :id => 'literature_contents'
  =f.actions do
    =f.submit literature.new_record? ? "Create" : "Update", :class => 'btn btn-primary'
    =link_to "Cancel", return_path(literature.class == Story ? poems_account_path(current_user) : stories_account_path(current_user)), :class => "btn"

#word_doc_uploader.modal.hide
  .modal-header
    =link_to 'x', '#', class:"close", data:{dismiss:"modal"}
    %h3 Upload a MS Word/OpenOffice Writer document
  -# This posts the form and has iframe-of-unlimited-doom load the resulting page. 
  -# It's a dirty, dirty hack to do file uploads with javascript.
  -# See assets/convert.js for wireup
  =form_tag convert_word_doc_path, :multipart => true, :target => 'iframe-of-unlimited-doom' do
    .modal-body
      %p Supported Document Formats:
      %ul
        %li Microsoft Word 2007/2010 (docx) 
        %li Microsoft Word 2003-97 (doc)
        %li Open Office/LibreOffice documents (odf)
        %li Rich Text Format (rtf)
        
      %label{:for => 'word_doc'} Document:
      =file_field_tag "word_doc"
    .modal-footer
      =submit_tag 'Upload', :class => 'btn btn-primary'
      =link_to 'Cancel', '#', class:"btn secondary", data:{dismiss:"modal"}


#please_wait.modal.hide
  .modal-header
    %h3 Please wait
  .modal-body
    %p Your request will be processed in the order it was recieved.
  .modal-footer

%iframe#iframe-of-unlimited-doom{:style => 'display:none;'}

app/views/shared/_report_link.html.haml
:ruby
  #required: favable or (@report and @reportable)
  #optional: button_size
  button_size ||= "mini"
  report = if @report # In watchescontroller
    reportable = @reportable
    @report.persisted? ? @report : nil
  elsif user_signed_in?
    current_user.reporting?(reportable)
  end
  js_id = String.random
  css = "btn btn-danger btn-#{button_size}"
%span{id:js_id}
  -if user_signed_in? 
    -if report
      =icon_link "flag icon-white", "Reported", '#', class:"#{css} disabled"
    -else
      =icon_link "flag icon-white", "Report", '#', class:css, data:{widget:"report-link", replace:"##{js_id}", class:reportable.class.name, id:reportable.id}
  -else
    Sign in to report

app/views/shared/_watch_link.html.haml
:ruby
  #required: watchable or (@watch and @watchable)
  #optional: button_size
  button_size ||= "mini"
  watch = if @watch # In watchescontroller
    watchable = @watchable
    @watch.persisted? ? @watch : nil
  elsif user_signed_in?
    current_user.watching?(watchable)
  end
  js_id = String.random
  css = "btn btn-info btn-#{button_size}"
%span{id:js_id}
  -if signed_in? 
    -if watch
      =icon_link "eye-close icon-white", "Unwatch #{watchable.class.name}", '#', class:css, data:{widget:"unwatch-link", replace:"##{js_id}", id:watch.id}
    -else
      =icon_link "eye-open icon-white", "Watch #{watchable.class.name}", '#', class:css, data:{widget:"watch-link", replace:"##{js_id}", class:watchable.class.name, id:watchable.id}
  -else
    Sign in to watch