config/routes.rb
Litsocial::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users, :only => []
  devise_scope :user do
    get     '/sign_in'         => 'devise/sessions#new',          as: :new_user_session
    post    '/sign_in'         => 'devise/sessions#create',       as: :user_session
    delete  '/sign_out'        => 'devise/sessions#destroy',      as: :destroy_user_session
    post    '/forgot_password' => 'devise/passwords#create',      as: :user_password
    get     '/forgot_password' => 'devise/passwords#new',         as: :new_user_password
    get     '/reset_password'  => 'devise/passwords#edit',        as: :edit_user_password
    put     '/reset_password'  => 'devise/passwords#update'
    post    '/sign_up'         => 'devise/registrations#create',  as: :user_registration
    get     '/sign_up'         => 'devise/registrations#new',     as: :new_user_registration

  end

  resources :stories do 
    member do 
      post :kindle
      get :kindle_preview
    end
  end
  resources :series do 
    member do 
      post :kindle
      get :kindle_preview
    end
  end
  resources :journals
  resources :pages, only: [:index, :show]
  resources :news_posts, only: [:index, :show], path: 'news' do 
    collection do 
      get :archive
    end
  end
  resources :users, only: [:index, :show] do 
    member do 
      get :stories
      get :series
      get :journals
    end
  end

  get 'forums/categories/:id' => 'forum_posts#category', as: :forum_category
  resources :forum_posts, path: 'forums'

  get 'account'         => 'account#show',    as: :account

  %w[stories journals forums watches favs bookmarks notifications edit cancel].each do |name|
    get "account/#{name}" => "account##{name}", as: "#{name}_account"
  end
  put 'account'         => 'account#update'
  delete 'account'      => 'account#destroy'

  resources :messages, :path => "/account/messages", except: [:edit, :update] do
    member do 
      put :report
      post :toggle
    end
    collection do 
      get :sent
      get :unread
      get :read
    end
  end
  resources :notifications, :path => '/account/notifications', only: [:destroy]
  resources :watches, only: [:create, :destroy]
  resources :favs, only: [:create, :destroy]
  resources :reports, only: [:create]

  get    'bookmarks/import' => 'bookmarks#import', as: :import_bookmarks
  post   'bookmarks/import' => 'bookmarks#import'
  put    'bookmarks/:story_id/:paragraph' => 'bookmarks#create_or_update', as: :bookmark
  delete 'bookmarks/:story_id' => 'bookmarks#destroy', as: :clear_bookmark

  resources :comments

  post 'convert_word_doc' => 'home#convert_word_doc', as: :convert_word_doc
  post 'user_lookup' => 'home#user_lookup', as: :user_lookup

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'pages'
  def index
    @stories = Story.includes(:user, :series).visible.sorted.limit(30)
    @news_posts = NewsPost.includes(:user).visible.sorted.limit(4)
    @forum_posts = ForumPost.includes(:user).visible.sorted.limit(6)
    @user = User.where(banned_at: nil).order(:id.desc).limit(15)
  end

  def convert_word_doc
    if params[:word_doc].respond_to? :tempfile
      file = File.join(Rails.root, "tmp", params[:word_doc].original_filename)
      begin
        FileUtils.cp(params[:word_doc].tempfile.path, file)
        @text = WordConverter.html_from_file(file)
      ensure
        FileUtils.rm(file)
      end
    else
      @text = params.inspect
    end
    @text = @text.html_safe
    render :layout => nil
  end

  def user_lookup
    render json: User.where(:name.like => "%#{params[:query]}%").pluck(:name)
  end
end

app/views/home/convert_word_doc.html.erb
<script>
  window.top.window.copy_text_from_iframe('#story_contents', "<%=escape_javascript @text %>");
</script>

app/views/home/index.html.haml
.row
  .span7

    %h1.title Welcome
    %p Lit Social is a place to read and share your stories

    %p Here's some stories that other people are sharing:
    %ul.unstyled
      -@stories.each do |story|
        %li #{link_to story.title, story} by #{user_link story.user}
      -if @stories.count > 30
        %li #{link_to "More Stories", stories_path(per_page: 30, page: 2)}

  .span3
    %h3.title.hidden-phone Latest News
    %h3.title.visible-phone=link_to "Latest News", news_posts_path
    %ul.unstyled
      -@news_posts.each do |post|
        %li #{link_to post.title, post} by #{user_link post.user}

    %h3.title.hidden-phone The Forum
    %h3.title.visible-phone=link_to "The Forum", forum_posts_path
    %ul.unstyled
      -@forum_posts.each do |post|
        %li #{link_to post.title, post} by #{user_link post.user}

    %h3.title New Users
    %ul.unstyled
      -@user.each do |user|
        %li=user_link user