config/routes.rb
Litsocial::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users, :only => []
  devise_scope :user do
    get     '/sign_in'         => 'devise/sessions#new',          as: :new_user_session
    post    '/sign_in'         => 'devise/sessions#create',       as: :user_session
    delete  '/sign_out'        => 'devise/sessions#destroy',      as: :destroy_user_session
    post    '/forgot_password' => 'devise/passwords#create',      as: :user_password
    get     '/forgot_password' => 'devise/passwords#new',         as: :new_user_password
    get     '/reset_password'  => 'devise/passwords#edit',        as: :edit_user_password
    put     '/reset_password'  => 'devise/passwords#update'
    post    '/sign_up'         => 'devise/registrations#create',  as: :user_registration
    get     '/sign_up'         => 'devise/registrations#new',     as: :new_user_registration

  end

  resources :stories do 
    member do 
      post :kindle
      get :kindle_preview
    end
  end
  resources :series do 
    member do 
      post :kindle
      get :kindle_preview
    end
  end
  resources :journals
  resources :pages, only: [:index, :show]
  resources :news_posts, only: [:index, :show], path: 'news' do 
    collection do 
      get :archive
    end
  end
  resources :users, only: [:index, :show] do 
    member do 
      get :stories
      get :series
      get :journals
    end
  end

  get 'forums/categories/:id' => 'forum_posts#category', as: :forum_category
  resources :forum_posts, path: 'forums'

  get 'account'         => 'account#show',    as: :account

  %w[stories journals forums watches favs bookmarks notifications edit cancel].each do |name|
    get "account/#{name}" => "account##{name}", as: "#{name}_account"
  end
  put 'account'         => 'account#update'
  delete 'account'      => 'account#destroy'

  resources :messages, :path => "/account/messages", except: [:edit, :update] do
    member do 
      put :report
      post :toggle
    end
    collection do 
      get :sent
      get :unread
      get :read
    end
  end
  resources :notifications, :path => '/account/notifications', only: [:destroy]
  resources :watches, only: [:create, :destroy]
  resources :favs, only: [:create, :destroy]
  resources :reports, only: [:create]

  get    'bookmarks/import' => 'bookmarks#import', as: :import_bookmarks
  post   'bookmarks/import' => 'bookmarks#import'
  put    'bookmarks/:story_id/:paragraph' => 'bookmarks#create_or_update', as: :bookmark
  delete 'bookmarks/:story_id' => 'bookmarks#destroy', as: :clear_bookmark

  resources :comments

  post 'convert_word_doc' => 'home#convert_word_doc', as: :convert_word_doc
  post 'user_lookup' => 'home#user_lookup', as: :user_lookup

  root :to => 'home#index'

end

app/models/story.rb
class Story < ActiveRecord::Base
  include Mixins::Taggable
  has_paper_trail
  attr_accessible :contents, :series_id, :series_position, :title, :remove_from_series
  attr_protected :user_id, :created_at, :updated_at, as: :admin

  acts_as_list column: :series_position, scope: :series
  include Mixins::Lockable


  scope :visible, where{ ((deleted == false) | (deleted == nil))  & (locked_at == nil) }
  scope :owner_visible, where{ (deleted == false) | (deleted == nil) } # Postgres doesn't select nulls if deleted != true

  scope :sorted, order(:id.desc)
  # Locked is a restricted name, used by AREL internally, see: https://github.com/rails/rails/issues/7421
  scope :is_locked, where{ locked_at == nil }
  scope :deleted, where{ deleted == true }

  belongs_to :series, counter_cache: true
  belongs_to :user
  has_many :bookmarks
  has_many :comments, :as => :commentable, :order => :id.asc

  validates :title, :contents, :user_id, presence: true
  validates :locked_reason, presence: true, if: :locked?
  validates_numericality_of :series_position, :message => "is not a number", allow_blank: true
  validate :series_belongs_to_same_owner_as_story

  attr_accessor :series_title
  before_save :save_series_title, if: ->(o){ o.series_id.blank? && o.series_title }
  before_save :update_word_count, if: :contents_changed?
  before_create :fix_acts_as_list
  before_update :fix_acts_as_list, if: :series_id_changed?

  def safe_contents
    MyHtmlSanitizer.clean contents
  end

  def visible?
    !(deleted? || locked?)
  end

  def next
    return unless series?
    self.class.visible.where(series_id: series_id, :series_position.gt => series_position).reorder(:series_position.asc).first
  end

  def prev
    return unless series?
    self.class.visible.where(series_id: series_id, :series_position.lt => series_position).reorder(:series_position.desc).first
  end

  def series?
    series_id
  end

  def remove_from_series
    series_id.nil?
  end

  def remove_from_series=(bool)
    return unless bool.to_i == 1
    self.series_id = nil
  end

  protected  
  def update_word_count
    # TODO: Add paragraph counter
    # Possible implementation: Load contents into nokogiri to count the number of p nodes?
    self.word_count = HTML::FullSanitizer.new.sanitize(self.contents || "").scan(/\w+(-\w+)?/).length
    self.paragraph_count = Nokogiri::HTML(MyHtmlSanitizer.basic_cleansing(self.contents)).search("/html/body/p").count
  end

  def fix_acts_as_list
    if series_id
      self.series_position = bottom_position_in_list.to_i + 1
    else
      self.series_position = nil
    end
  end

  def save_series_title
    # Need to manually save since the autosave callbacks have already been called.
    self.series_id = user.series.find_or_create_by_title(series_title).try(:id)
  end

  def series_belongs_to_same_owner_as_story
    errors.add :series_id, "Series must belong to the same user" unless series.nil? || series.user == user
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  require_login except: [:index, :show]
  before_filter :find_story, except:[:index, :new, :create]
  before_filter :check_owner, only: [:edit, :update, :destroy]
  before_filter :block_edit_if_locked, only:[:edit, :update]

  def index
    @stories = paged(Story.visible.includes(:series, :user))
  end

  def show
    if !@story.visible? && !owner?(@story)
      render 'errors/story_403', status: 403
    else
      @user = @story.user
      render layout: 'users'
    end
  end

  def kindle
    if not @story.visible?
      render json:{status: "error", error: "Story not visible." }
    elsif not current_user.kindle?
      render json:{status: "error", error: "You don't have a kindle email configured." }
    else
      KindleMailer.story_email(current_user.kindle_email, @story).deliver
      render json:{status: "ok", message: "Story sent!" }
    end
  end

  def kindle_preview
    if not @story.visible?
      show403 "Story not available"
    else
      render text: KindleHtml::StoryWriter.new(@story).to_html
    end
  end

  def new
    @story = current_user.stories.build(series_id: params[:series])
  end

  def create
    @story = current_user.stories.build(params[:story])
    if @story.save
      redirect_to return_path(@story), notice: "Story saved!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @story.update_attributes(params[:story])
      redirect_to return_path(@story), notice: "Story updated!"
    else
      render :edit
    end
  end

  def destroy
    @story.update_column :deleted, true
    redirect_to return_path(account_path), alert: "Story deleted"
  end

  private
  def find_story
    @story = Story.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render 'errors/404', locals: {thing: "Story"}
  end

  def check_owner
    redirect_to account_path, alert: "Not your story!" unless owner?(@story)
  end

  def block_edit_if_locked
    render 'errors/story_403' if @story.locked? || @story.deleted?
  end
end

app/views/stories/_form.html.haml
%p 
  If you don't want to deal with copying and pasting your story, you can 
  =link_to "upload an MS Word or OpenOffice Writer document", '#', data:{target:'#word_doc_uploader', toggle:'modal'}
  and we'll copy and paste the text for you.

=simple_form_for @story, html:{class:'form-horizontal'}  do |f|
  =f.input :title
  =f.input :contents, input_html:{class: 'redactor'}
  =f.input :tag_list, hint: "Comma seperated. All tags converted to dashed-lower-case "
  =f.association :series, label: "Add to Series", include_blank: "(None or New Series)"
  =f.input :series_title, label: "Title for New Series", hint: "Leave blank if you don't want to add the story to a series"
  .form-actions
    =f.submit class: 'btn btn-primary'
    =link_to "Cancel", return_path(account_path(current_user)), class: 'btn'
    -unless @story.new_record?
      =link_to "Delete", story_path(@story, return: return_path(account_path)), method: :delete, confirm: "Are you sure you want to delete this story?",class: 'pull-right btn btn-danger'

#word_doc_uploader.modal.hide
  .modal-header
    =link_to 'x', '#', class:"close", data:{dismiss:"modal"}
    %h3 Upload a MS Word/OpenOffice Writer document
  -# This posts the form and has iframe-of-unlimited-doom load the resulting page. 
  -# It's a dirty, dirty hack to do file uploads with javascript.
  -# See assets/convert.js for wireup
  =form_tag convert_word_doc_url, :multipart => true, :target => 'iframe-of-unlimited-doom' do
    .modal-body
      %p Supported Document Formats:
      %ul
        %li Microsoft Word 2007/2010 (docx) 
        %li Microsoft Word 2003-97 (doc)
        %li Open Office/LibreOffice documents (odf)
        %li Rich Text Format (rtf)
        
      %label{:for => 'word_doc'} Document:
      =file_field_tag "word_doc"
    .modal-footer
      =submit_tag 'Upload', :class => 'btn btn-primary'
      =link_to 'Cancel', '#', class:"btn btn-secondary", data:{dismiss:"modal"}

%iframe#iframe-of-unlimited-doom{:style => 'display:none;'}

app/views/stories/_series_list.html.haml
:ruby
  # required: @story or [series, current_story]
  if @story
    series = @story.series
    current_story = story
  else 
    current_story ||= nil
  end

%h3
  %small Series:
  =link_to series.title, series
%ol
  -series.stories.visible.each do |story|
    %li{value: story.series_position}
      -if current_story == story
        %strong=sicon_link :story, story.title, story
      -else
        =sicon_link :story,  story.title, story

app/views/stories/_series_next_prev.html.haml
-# required: story
-if series = story.series
  .row-fluid{style: "text-align: center;"}
    .span4
      -if prev_story = story.prev
        %strong Prev
        =sicon_link :story, prev_story.title, prev_story
      -else
        &nbsp;
    .span4
      %strong #{"##{story.series_position}"} of
      =sicon_link :series, series.title, series
    .span4
      -if next_story = story.next
        %strong Next
        =sicon_link :story, next_story.title, next_story
      -else
        &nbsp;

app/views/stories/edit.html.haml
%h1 Edit Story: #{@story.title}
%hr.slim
=render 'form'

app/views/stories/index.html.haml
%h2 
  Stories
  -if false #user_signed_in?
    .pull-right.hidden-phone
      =link_to "New Story", new_story_path, class:'btn btn-success btn-mini'
-if @stories
  %table.table.stories
    %thead
      %th Title
      %th Word Count
      %th Author
      %th Posted At
    %tbody
      -@stories.each do |story|
        %tr
          %td
            %strong=sicon_link :story, story.title, story
          %td=story.word_count
          %td=user_link story.user
          %td
            %span.muted=dt(story.created_at)
  =paginate @stories
-else
  %p Nothing has been submitted yet.

app/views/stories/new.html.haml
%h1 New Story
%hr.slim
=render 'form'

app/views/stories/show.html.haml
=render 'shared/banners', record: @story
%article.story

  =render 'series_next_prev', story: @story
  
  %h1.text-center=h @story.title
  %p.meta.text-center
    %span.muted
      Posted 
      =dt(@story.created_at)
      by #{user_link @story.user}
      -if signed_in? && current_user.kindle?
        |
        -if @story.series
          =icon_link "book", "Send Series to Kindle", '#', class: "btn btn-mini", data:{widget: "send-to-kindle", word:"Series", url: kindle_series_path(@story.series)}
        -else
          =icon_link "book", "Send Story to Kindle", '#', class: "btn btn-mini", data:{widget: "send-to-kindle", word:"Story", url: kindle_story_path(@story)}
  -if bookmark = bookmark_for(@story)
    %p#bookmark-message
      %strong
        You've saved your place
      =icon_link "bookmark", "Continue Reading", "#paragraph-#{bookmark}"
      %strong or
      =icon_link "remove", "Remove Bookmark", '#', id:"clear_bookmark"
      %strong ?

  .rich#story-text{data: {story_id: @story.id, position: bookmark}}=rich @story.contents

  =render 'series_next_prev', story: @story

-if signed_in?
  .centered-ul-wrapper{style: "margin: 1em 0;"}
    %ul.inline
      %li=render 'shared/watch_link', watchable: @story.user, button_size: "small"
      -if @story.series?
        %li=render 'shared/watch_link', watchable: @story.series, button_size: "small"
      %li=render 'shared/fav_link', favable: @story, button_size: "small"
      %li=render 'shared/report_link', reportable: @story, button_size: "small"

=comments_for @story