config/routes.rb
Litsocial::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users, :only => []
  devise_scope :user do
    get     '/sign_in'         => 'devise/sessions#new',          as: :new_user_session
    post    '/sign_in'         => 'devise/sessions#create',       as: :user_session
    delete  '/sign_out'        => 'devise/sessions#destroy',      as: :destroy_user_session
    post    '/forgot_password' => 'devise/passwords#create',      as: :user_password
    get     '/forgot_password' => 'devise/passwords#new',         as: :new_user_password
    get     '/reset_password'  => 'devise/passwords#edit',        as: :edit_user_password
    put     '/reset_password'  => 'devise/passwords#update'
    post    '/sign_up'         => 'devise/registrations#create',  as: :user_registration
    get     '/sign_up'         => 'devise/registrations#new',     as: :new_user_registration

  end

  resources :stories do 
    member do 
      post :kindle
      get :kindle_preview
    end
  end
  resources :series do 
    member do 
      post :kindle
      get :kindle_preview
    end
  end
  resources :journals
  resources :pages, only: [:index, :show]
  resources :news_posts, only: [:index, :show], path: 'news' do 
    collection do 
      get :archive
    end
  end
  resources :users, only: [:index, :show] do 
    member do 
      get :stories
      get :series
      get :journals
    end
  end

  get 'forums/categories/:id' => 'forum_posts#category', as: :forum_category
  resources :forum_posts, path: 'forums'

  get 'account'         => 'account#show',    as: :account

  %w[stories journals forums watches favs bookmarks notifications edit cancel].each do |name|
    get "account/#{name}" => "account##{name}", as: "#{name}_account"
  end
  put 'account'         => 'account#update'
  delete 'account'      => 'account#destroy'

  resources :messages, :path => "/account/messages", except: [:edit, :update] do
    member do 
      put :report
      post :toggle
    end
    collection do 
      get :sent
      get :unread
      get :read
    end
  end
  resources :notifications, :path => '/account/notifications', only: [:destroy]
  resources :watches, only: [:create, :destroy]
  resources :favs, only: [:create, :destroy]
  resources :reports, only: [:create]

  get    'bookmarks/import' => 'bookmarks#import', as: :import_bookmarks
  post   'bookmarks/import' => 'bookmarks#import'
  put    'bookmarks/:story_id/:paragraph' => 'bookmarks#create_or_update', as: :bookmark
  delete 'bookmarks/:story_id' => 'bookmarks#destroy', as: :clear_bookmark

  resources :comments

  post 'convert_word_doc' => 'home#convert_word_doc', as: :convert_word_doc
  post 'user_lookup' => 'home#user_lookup', as: :user_lookup

  root :to => 'home#index'

end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  require_login except: [:index, :show]
  before_filter :find_series, except:[:index, :new, :create]
  before_filter :check_owner, only: [:edit, :update, :destroy]

  def index
    @series = paged(Series.includes(:user))
  end

  def show
    @series = Series.find(params[:id])
    if !@series.visible? && !owner?(@series)
      show403 "Series not available"
    else
      @user = @series.user
      render layout: 'users'
    end  
  end

  def kindle
    if not @series.visible?
      render json:{status: "error", error: "Series not visible." }
    elsif not current_user.kindle?
      render json:{status: "error", error: "You don't have a kindle email configured." }
    else
      KindleMailer.series_email(current_user.kindle_email, @series).deliver
      render json:{status: "ok", message: "Series sent!" }
    end
  end

  def kindle_preview
    if not @series.visible?
      show403 "Series not available"
    else
      render text: KindleHtml::SeriesWriter.new(@series).to_html
    end
  end

  def new
    @series = current_user.series.build
  end

  def create
    @series = current_user.series.build(params[:series])
    if @series.save
      redirect_to return_path(@series), notice: "Series saved!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @series.update_attributes(params[:series])
      redirect_to return_path(@series), notice: "Series updated!"
    else
      render :edit
    end
  end

  def destroy
    @series.destroy
    redirect_to return_path(account_path), alert: "Series deleted"
  end

  private
  def find_series
    @series = Series.find(params[:id])
  end

  def check_owner
    redirect_to account_path, alert: "Not your series!" unless owner?(@series)
  end
end

app/views/series/_form.html.haml
=simple_form_for @series, html:{class:'form-horizontal'}  do |f|
  =f.input :title
  %h3.title Stories in this Series
  =f.fields_for :stories do |ff|
    %h4=ff.object.title
    =ff.input :series_position, label: "Chapter Number"
    =ff.input :remove_from_series, as: :boolean, label: "Remove from Series"
  .form-actions
    =f.submit class: 'btn btn-primary'
    =link_to "Cancel", return_path(account_path), class: 'btn'
    -unless @series.new_record?
      =link_to "Delete", series_path(@series, return: return_path(account_path)), method: :delete, confirm: "Are you sure you want to delete this series? (The stories won't be deleted)",class: 'pull-right btn btn-danger'

app/views/series/edit.html.haml
%h1 Edit Story: #{@series.title}
%hr.slim
=render 'form'

app/views/series/index.html.haml
%h2 Series
-if @series
  %table.table.stories
    %thead
      %tr
        %th Title
        %th.hidden-phone # of Stories
        %th Author
        %th.hidden-phone Created
    %tbody
      -@series.each do |s|
        %tr
          %td=sicon_link :series, s.title, s
          %td.hidden-phone=s.stories_count
          %td=user_link s.user
          %td.hidden-phone=dt s.created_at

  =paginate @series
-else
  %p Nothing has been submitted yet.

app/views/series/new.html.haml
%h1 New Series
%hr.slim
=render 'form'

app/views/series/show.html.haml
=render 'shared/banners', record: @series
%section.white-box
  %h3=@series.title
  %p.meta
    %span.muted
      Posted 
      =dt(@series.created_at)
      %span.visible-phone by #{user_link @series.user}
  %table.table.stories
    %thead
      %th Chapter
      %th Title
      %th Word Count
      %th Posted At
    %tbody
      -@series.stories.visible.each do |s|
        %tr
          %td=s.series_position
          %td
            %strong=sicon_link :story, s.title, s
          %td=s.word_count
          %td
            %span.muted=dt s.created_at

  %ul.inline
    %li=render 'shared/watch_link', watchable: @series
    %li=render 'shared/fav_link', favable: @series
    %li=render 'shared/report_link', reportable: @series